
class Programmer: 
    company = "Microsoft"

    def __init__(self, salary, name, pincode):
        self.salary = salary
        self.name = name
        self.pincode = pincode 
#Employee 1
k = Programmer(13000000, "Kunal", 120081)
print(( "Name is :",k.name ,"Salary is :",k.salary , "Pincode is :" ,k.pincode , "Company name is :",k.company))
print()
#Employee 2
r = Programmer(10000000, "Rohan", 870081)
print(( "Name is :",r.name ,"Salary is :",r.salary , "Pincode is :" ,r.pincode , "Company name is :",r.company))
print()
#Employee 3
l = Programmer(11000000, "Lucky", 300081)
print(( "Name is :",l.name ,"Salary is :",l.salary , "Pincode is :" ,l.pincode , "Company name is :",l.company))
print()
a = Programmer(12000000, "Anil", 524001)
print(( "Name is :",a.name ,"Salary is :",a.salary , "Pincode is :" ,a.pincode , "Company name is :",a.company))
print()
#Employee 4
p = Programmer(15000000, "Pooja", 598001)
print(( "Name is :",p.name ,"Salary is :",p.salary , "Pincode is :" ,p.pincode , "Company name is :",p.company))
print()
